### PR TITLE
Improve user management.

### LINKED ISSUE #101: Should we allow editors to view list of users?
A common cause of confusion and support requests is that users with the "editor" role are unaware of who has a user account on the website and what role/permissions each user has.

Should we allow users with the "editor" role to (only) view the list of users at `/admin/people`?

### LINKED ISSUE #148: Improve user management.
- [x] ~~Randomize user 1 name~~
- [x] Disable user 1 edit form fields 
~~Swap roleassign for role delegation (roleassign is blocking #101)~~

https://www.drupal.org/node/947312

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #148. Resolves #101.

This removes roleassign and userprotect in favor of administerusersbyrole (https://www.drupal.org/project/administerusersbyrole). With this setup, it is no longer necessary to grant webmasters (or other roles) the 'administer users' permission.

### CODE REVIEW

**Comment by richardbporter** [comment]
Test failure related to: https://www.drupal.org/project/administerusersbyrole/issues/3010662

**Comment by richardbporter** [comment]
Requires core patch: https://www.drupal.org/node/2854252

**Comment by richardbporter** [comment]
It seems like this also resolves #147 - I can no longer reproduce it on this branch.

**Comment by richardbporter** [comment]
A manual test would be nice if anyone has time.

**Comment by richardbporter** [comment]
Thanks for testing this.

See this regarding user 1 name: https://github.com/uiowa/rusty/issues/148#issuecomment-434322995

I've got a fix for #147 in-progress on this branch. Then we can merge.

**Comment by genjohnson** [comment]
@richardbporter How does a webmaster or editor create a new user account with this setup? I no longer see the "Add user" button on the People page when logged in as a webmaster or editor.

**Comment by genjohnson** [comment]
@richardbporter I'm fine with this approach, and it's working as expected for me except that Webmasters still cannot access the "add user" button/get an access denied message when going to admin/people/create.

There's a closed issue related to this: https://www.drupal.org/project/administerusersbyrole/issues/2996965

I see where they've implemented hook_entity_create_access() in administerusersbyrole.module, but with the debugging I've tried it seems that the function isn't being called.

**Comment by genjohnson** [comment]
Maybe we need to apply the [patch from the referenced issue](https://www.drupal.org/project/drupal/issues/2854252#comment-12774564), which has been committed to 8.7?... I will give this a try.

**Comment by richardbporter** [comment]
Yes, sorry forgot to document that!

https://github.com/uiowa/uiowa/pull/18

**Comment by genjohnson** [comment]
Sweet, it works with the core patch :) I'll work on merging this & [uiowa/uiowa#18](https://github.com/uiowa/uiowa/pull/18)

**Pull request merged**
