### PR TITLE
Move uiowa_paragraphs into separate module and have it contain its own config

### PR DESCRIPTION
**Pull request by pyrello**
This PR is for moving config for uiowa_paragraphs back into the module itself and then moving the module into a new separate project: [uiowa/uiowa_paragraphs](https://github.com/uiowa/uiowa_paragraphs).

The rationale behind this is that uiowa_paragraphs cannot be shared between multiple profiles if it lives inside of rusty. Additionally, for it to be its own project, its config needs to be self-contained. The new uiowa_paragraphs project will only install the different paragraph types. It will not add a section field to an existing content type or create a new content type with that field. That remains the purview of the profile.

This is my first PR, so any feedback on how I could improve it would be welcome.

### CODE REVIEW

**Comment by pyrello** [comment]
FYI, I have not removed the paragraph-related config files from config/sync yet. When I tested installation, it didn't seem to matter that they were duplicated, but I'm assuming that we won't want them in the profile also.

**Comment by adamdelaney** [comment]
My understanding is that paragraphs config will remain in Rusty's profile sync directory. This will allow us to track config changes using Drupal's built in CM tooling. Additionally, changes have gone into the paragraphs within the last 24 hours so we would want to reflect any code changes if the module code is moved into a separate repo.

**Comment by pyrello** [comment]
@adamdelaney I have not been able to figure out how to get around having the duplicate config, so for the moment I am inclined to agree that it has to work that way.

I'll include updates in this PR as soon as I have time.

**Comment by pyrello** [comment]
There seems to be an issue with requiring this pull request. When requiring this version in the uiowa app, it complains that there is no master branch of uiowa/uiowa_paragraphs. This happened at first when I was trying to test it and I was able to get it to work after running `composer clearcache`. However, @joewhitsitt also saw this error yesterday and running the above command didn't fix it. So I'm not sure what the issue is yet.

Also, there are conceptual issues with the approach that I am advocating for with this PR and our current config management strategy. My ideal was to move all the paragraphs-related configuration to the separate uiowa_paragraphs module and to leave the page creation to rusty. Since we are using the config/sync directory to install new sites from an existing configuration, the order in which operations occurs means that the import of profile configuration happens before any modules are installed. This causes the import to fail because the rusty config includes the field on the page which is expecting the section paragraph type to already exist.

One idea about how this could work differently without changing the current approach would be to move the page creation config to the optional directory of the uiowa_paragraphs module. I don't love this approach, since I don't think the page creation logic should live there, but it might work.

Alternately, I'm going to see if there is a different way of accomplishing the initial site install from configuration that still checks all the boxes from the discussion here: https://github.com/uiowa/rusty/issues/158

Either way, don't bother with testing this PR at this point. Its not ready. I'll either delete it or request a review based on what I come up with.

**Comment by pyrello** [comment]
I am going to approach this in a different way. The combination of moving the uiowa_paragraphs module out of rusty and implementing changes to the way the configuration is handled should probably be separate PRs.

**Pull request closed without merging**
