### PR TITLE
UIowa Events

### PR DESCRIPTION
**Pull request by joewhitsitt**
Initial work on uiowa_events for D8 that was started before #173 was created.

Currently turns on the main module and sub modules on install which creates the events instance entity type and the custom block type, paragraph type (uiowa_events_paragraph), page configuration (uiowa_events_page).

**Note:** _The events instance entity type was created to create one widget form that can be used in several places (block, paragraph, page). At this time, it might be worth looking at turning it into a node type instead to simplify the code. Also, the custom block type could be abstracted to just be an inline entity form for all node types._

## Testing:

- Create custom block
- Create paragraph item
- Configure events page by referencing an existing events instance (/admin/content/events/add, or previously created block/paragraph). admin/config/system/uiowa-events

## Known Issues:

- [x] The chosen implementation (block) is broken because Rusty has global config set. This might change with #225.
- [ ] ~~Not sure how best to handle number of events, events per page configuration depending on where the events instance is used.~~ _Removed pager functionality for MVP._

### CODE REVIEW

**Comment by richardbporter** [comment]
Some initial thoughts as I work through this:

- The terminology 'events instance' is really confusing because something very similar is used to describe individual event dates in the API: https://content.uiowa.edu/events-api/events I think we should avoid that and call it something else. It seems more like configuration to me.
-- Is there a way to use configuration instead?
- I'm not able to reference an 'events instance' when creating a custom block or paragraph entity, only on the configuration page. Should this be possible?

**Comment by richardbporter** [comment]
I think in general it would be nice if we could simplify this module. I'm not sure it needs all the configuration from the D7 version. For example, given the paragraph entity why is it necessary to have a page submodule at all? Not having one might actually jive better with config split since "turning things off" could be a challenge.

**Comment by joewhitsitt** [comment]
i got some responses:

- I wasn't very fond of 'events instance' either when I typed it. open to suggestions.
- i don't think we can go the config way if we want to use the field API. i heard desire at the time to "keep it simple" but it may have gotten complex in another way. https://www.drupal.org/node/1833872
- only inline entity form add on block and paragraph - yes, working as configured. I thought it simplified the process a bit only to complicate the uiowa_events_page form with a reference field...
- good point about the possibility of no page. this would work IMO if we didn't need the day/week/month/etc. functionality pages later on and the more link could be a user defined link.

**Comment by joewhitsitt** [comment]
BTW, thanks for taking a look at this! We could completely dump it and start over if you really want. It is my first d8 module/port. I want to get this or something else out for events ASAP!

**Comment by richardbporter** [comment]
I think we should delete the uiowa_events_page submodule and allow content editors to embed event listings as needed. With the default configuration set to link off of the site, the base uiowa_events module would be fairly un-opinionated and could be installed by default without the need to uninstall it.

Additionally, the events instance should be renamed to avoid confusion with the content.uiowa.edu API.

Further simplifications could include:

- Delete the block implementation.
- Delete the custom entity and attach fields to paragraph entity. 
- Move the paragraph implementation to uiowa_paragraphs.
- Possibly move the uiowa_events module out of rusty.

@adamdelaney - @joewhitsitt and I were hoping you could weigh in here with your opinion.

**Comment by richardbporter** [comment]
Deleting the page module will require us to re-implement the pager and a generic link field on the instance entity.

**Comment by richardbporter** [comment]
IEF is making states manipulation a nightmare. :(

**Comment by joewhitsitt** [comment]
I think this is working as expected except for the paging stuff. For MVP, we could treat the paragraph item similar to the D7 panel pane and just have a number of events option. We can then take more time to look into paging/caching in D8. I can work on ripping that stuff out for now.

Naming conventions were brought up offline. The main thing is that this module still uses a Custom Content Entity

Label = Events Instance
entity type = uievents
bundle = uievents

I am open to other suggestions about these. Unlike Article, etc. a single instance of this content is a collection of separate events based on filters provided.

**Comment by joewhitsitt** [comment]
- Ripped out the pager stuff for now, fixed more link on paragraph/block.
- I changed some of the Events Instances labels, etc. to Event Feed. This appears to be a non-breaking change. If additional renaming is desired, it might make sense to regenerate the custom entity and move code over.
- Also added permissions.

I think this MVP is ready for testing/merging. After that this will need docs, styles.

**Pull request merged**
