### PR TITLE
Features paragraphs

### PR DESCRIPTION
**Pull request by adamdelaney**

### CODE REVIEW

**Comment by adamdelaney** [comment]
`drush features:import:all` does not revert features.

**Comment by richardbporter** [comment]
I'm seeing that same error locally: `User warning: The following theme is missing from the file system: uiowa_paragraphs in drupal_get_filename() (line 276 of core/includes/bootstrap.inc).`

**Comment by richardbporter** [comment]
I don't understand the benefit of packaging these up into separate modules. If I disable uiowa_paragraphs_card for example, it overrides the feature.

**Comment by richardbporter** [comment]
The theme error is probably caused by: https://github.com/uiowa/rusty/blob/082451205638cdea7083d760712e9921121b4dbf/modules/uiowa_paragraphs/uiowa_paragraphs_core/uiowa_paragraphs_core.module#L50

I can't get any features Drush command to "revert" a feature.

**Comment by richardbporter** [comment]
I think we're closing this in favor of a config split workflow. I'll leave the branch.

**Pull request closed without merging**
