### PR TITLE
test update hook

### PR DESCRIPTION
**Pull request by joewhitsitt**
For HR's config split to work, graylist_skip_equal needs to be set to false. This PR sets that in config but also helps us test an update hook for existing installs.

After site install, I created an update hook to change this configuration on the site.

- `drush cr`
- `drush updb`

I saw the change within the site UI and a diff was reported with `drush cst`

`drush cex` then exported "config_split.config_split.site" to the site config directory.

The updb also ran on the HR site, but since it already had the config set to false, there was no diff.

### CODE REVIEW

**Comment by richardbporter** [comment]
What was it again about HR that needed this?

**Comment by richardbporter** [comment]
I tested this on a site with no split config and just ran `config:import` to get the change on the split. Ran the db update afterwards with no change. I'm not sure of the order of operations there but either way it worked.

**Comment by richardbporter** [comment]
I'm just trying to understand why we want this change. It seems like `Split only when different` would be beneficial to minimize config differences.

**Comment by adamdelaney** [comment]
I'm fine with leaving this on for now. This could have been a symptom of not understanding weight and config_filters.

**Comment by richardbporter** [comment]
Ok - I'll close this for now. If we run into it again, we can enable it for default config.

@joewhitsitt FYI HR has this exported in dev: https://github.com/uiowa/hr.uiowa.edu/blob/develop/config/config_split.config_split.site.yml#L26

**Pull request closed without merging**
