### PR TITLE
Env splits

### PR DESCRIPTION
**Pull request by adamdelaney**

### CODE REVIEW

**Comment by adamdelaney** [comment]
relies on https://github.com/uiowa/multisite/pull/88

**Comment by richardbporter** [comment]
I changed the split names to match our environment machine names. I also put them in a subfolder called 'splits'.

Its a bit of a pain to configure each AC split with the same, or almost the same, config. Maybe we will do more for dev in the future (enable field_ui) but we could almost live with just a local and cloud split.

**Comment by richardbporter** [comment]
Looks like GA and Acquia connector are already overridden in dev/test to not do anything:

https://github.com/uiowa/rusty/blob/master/modules/uiowa_seo/src/ConfigOverrides/GoogleAnalyticsOverride.php#L22
https://github.com/uiowa/rusty/blob/master/src/ConfigOverride/AcquiaConnectorOverride.php

We could remove that code and go the split route or combine the cloud splits and leave it.

**Comment by richardbporter** [comment]
Also, we should write a test to ensure that these splits are never exported as active.

**Comment by richardbporter** [comment]
We'll revisit this at a later date.

**Pull request closed without merging**
