### PR TITLE
Uiowa footer

### PR DESCRIPTION
**Pull request by genjohnson**
This PR adds the uiowa_footer module, which is based on the D7 version of [sitenow_footer](https://github.com/ITS-UofIowa/sitenow_custom_profile/tree/7.x-3.x/modules/custom/sitenow_footer).

For details, see the [uiowa_footer README](https://github.com/uiowa/rusty/blob/uiowa_footer/modules/uiowa_footer/README.md).

There's some follow-up work that will need to happen in regards to the styling (and likely the default template file) when work on a base theme gets going, so please don't worry too much about that now.

Also, I'm not sure if a block is the best approach to rendering the output and have opened follow-up issue #117 to discuss this.

### CODE REVIEW

**Comment by genjohnson** [comment]
I'm not sure a block is necessary if we're using hook_page_bottom.

**Comment by richardbporter** [comment]
I would agree. Turns out the error is related to the block not being placed.

A block would make sense if the configuration lived with it.

**Comment by adamdelaney** [comment]
It probably could. You could have a footer block type. I'm not sure what the use case would be, or why you would need multiple footers.

**Comment by adamdelaney** [comment]
I would suggest a theme function however, in case you would want to preprocess or process the variables.

**Pull request merged**
