### PR TITLE
Node teaser

### LINKED ISSUE #149: field_teaser tasks
- [x] Set field_teaser as default metatag description for basic pages.
- [x] Move field_teaser to vertical fieldset. Since this is not being rendered on the node and for all intensive purposes metadata we should move it out of the main layout area.
- [x] Provide description text for the field. Our goal with D8 is to document as much information within the site, so providing context to how this field is used with field description makes the most sense.

### PR DESCRIPTION
**Pull request by adamdelaney**
This PR resolves #149.

### CODE REVIEW

**Comment by pyrello** [comment]
screen shot 2018-11-16 at 2 51 42 pm

The teaser field is showing up correctly on the node creation page, in the Content Description field group, but not on the node edit page where it just shows up as a normal field.

As an unrelated side note, why is this field called "field_teaser" with the label "Teaser"? That seems a little confusing considering the different use of the term "teaser" in the Drupal ecosystem.

**Comment by adamdelaney** [comment]
@pyrello nice catch. Looks like D8 has 2 forms. 1 for node creation and 1 for edit.

**Comment by richardbporter** [comment]
> As an unrelated side note, why is this field called "field_teaser" with the label "Teaser"? That seems a little confusing considering the different use of the term "teaser" in the Drupal ecosystem.

I _think_ because it could be used in teaser views if set but I'm not 100% on that.

**Comment by joewhitsitt** [comment]
[9-19 notes](https://github.com/uiowa/rusty/wiki/D8-Check-in-notes):

> Unlike the Section bundle provided by SiteNow Paragraphs for D7, the Section bundle in D8 will not include title and body (WYSIWYG) fields. Instead, a plain text "Teaser" field will be provided directly on the content type. This will allow for:
> 
> - increased consistency
> - a unified way for users of different sites to complete a task
> - decreases the support burden
>
> the teaser text can easily be used for a variety of things, including:
> - as the meta description of the full page display
> - as teaser text in other display modes (e.g., on a card)

**Comment by adamdelaney** [comment]
I'm open to changing the field name/label if we think that we can come up with a better one.

**Pull request merged**
